# ---- Column keys ----
ID_DATA_KEY = "id"
DATE_DATA_KEY = "date"
GAME_ID_DATA_KEY = "game_id"
LEVEL_DATA_KEY = "level_id"	
GAME_TIME_DATA_KEY ="game_time"
GAME_PROGRESSION_DATA_KEY = "progression"
ACTION_DATA_KEY = "action_name"
OBJECT_DATA_KEY = "object_name"
DURATION_DATA_KEY = "duration"
CODE_DATA_KEY = "code"
VALUE_DATA_KEY = "value"
REASON_DATA_KEY = "reason_name"
ERROR_MESSAGE_DATA_KEY ="error_message"
X_POS_DATA_KEY = "x_pos";
Y_POS_DATA_KEY = "y_pos";
FLIPPED_DATA_KEY = "flipped";
OWNED_KEY_DATA_KEY = "owned_key"
# Added during processing
GROUP_ID_DATA_KEY = "group_id"
STUDENT_ID_DATA_KEY = "student_id"


INTERACTION_DATA_KEYS = [
    ID_DATA_KEY,
    DATE_DATA_KEY,
    GAME_ID_DATA_KEY,
    LEVEL_DATA_KEY,
    GAME_TIME_DATA_KEY,
    GAME_PROGRESSION_DATA_KEY,
    ACTION_DATA_KEY,
    OBJECT_DATA_KEY,
    DURATION_DATA_KEY,
    CODE_DATA_KEY,
    VALUE_DATA_KEY,
    REASON_DATA_KEY,
    ERROR_MESSAGE_DATA_KEY,
    X_POS_DATA_KEY,
    Y_POS_DATA_KEY,
    FLIPPED_DATA_KEY,
    OWNED_KEY_DATA_KEY,
]

# ---- Column values ----

# ACTION values 
DISPLAYED_ACTION = "DISPLAYED"
COPIED_ACTION = "COPIED"
PASTED_ACTION = "PASTED"
LAUNCHED_ACTION = "LAUNCHED"
STARTED_ACTION = "STARTED"
ENDED_ACTION = "ENDED"
RESTARTED_ACTION = "RESTARTED"
RESUMED_ACTION = "RESUMED"
LEAVED_ACTION = "LEAVED"
CHANGED_ACTION = "CHANGED"
ASKED_ACTION = "ASKED"
RECEIVED_ACTION = "RECEIVED"

# OBJECT values 
# (DISPLAYED / COPIED)
BASE_PROGRAM_SECTION_OBJECT = "BASE_PROGRAM_SECTION"
BASE_ERROR_SECTION_OBJECT = "BASE_ERROR_SECTION"
BASE_STRUCTURE_SECTION_OBJECT = "BASE_STRUCTURE_SECTION"
BASE_COMMENT_SECTION_OBJECT = "BASE_COMMENT_SECTION"
VAR_CREATION_SECTION_OBJECT = "VAR_CREATION_SECTION"
VAR_MODIFICATION_SECTION_OBJECT = "VAR_MODIFICATION_SECTION"
VAR_USAGE_SECTION_OBJECT = "VAR_USAGE_SECTION"
VAR_TYPE_SECTION_OBJECT = "VAR_TYPE_SECTION"
CONDI_1BRAN_SECTION_OBJECT = "CONDI_1BRAN_SECTION"
CONDI_2BRAN_SECTION_OBJECT = "CONDI_2BRAN_SECTION"
CONDI_3BRAN_SECTION_OBJECT = "CONDI_3BRAN_SECTION"
FOR_SIMPLE_SECTION_OBJECT = "FOR_SIMPLE_SECTION"
FOR_COUNTER_0_SECTION_OBJECT = "FOR_COUNTER_0_SECTION"
FOR_COUNTER_N_SECTION_OBJECT = "FOR_COUNTER_N_SECTION"
WHILE_SIMPLE_SECTION_OBJECT = "WHILE_SIMPLE_SECTION"
ABOUT_RESEARCH_SECTION_OBJECT = "ABOUT_RESEARCH_SECTION"
ABOUT_DATA_SECTION_OBJECT = "ABOUT_DATA_SECTION"
ABOUT_RESOURCES_SECTION_OBJECT = "ABOUT_RESOURCES_SECTION"
# (COPIED)
CODE_EDITOR_SECTION_OBJECT = "CODE_EDITOR_SECTION"
CONTROL_FUNCTION_SECTION_OBJECT = "CONTROL_FUNCTION_SECTION"
ASSISTANT_MESSAGES_SECTION_OBJECT = "ASSISTANT_MESSAGES_SECTION"
# (PASTED)
CONTENT_OBJECT = "CONTENT"
# (LAUNCHED)
FULLY_EXECUTED_PROGRAM_OBJECT = "FULLY_EXECUTED_PROGRAM"
USER_STOPPED_PROGRAM_OBJECT = "USER_STOPPED_PROGRAM"
LEVEL_LOST_PROGRAM_OBJECT = "LEVEL_LOST_PROGRAM"
TOO_MANY_LINES_ERROR_PROGRAM_OBJECT = "TOO_MANY_LINES_ERROR_PROGRAM"
GAME_ERROR_PROGRAM_OBJECT = "GAME_ERROR_PROGRAM"
SYNTACTIC_ERROR_PROGRAM_OBJECT = "SYNTACTIC_ERROR_PROGRAM"
SEMANTIC_ERROR_PROGRAM_OBJECT = "SEMANTIC_ERROR_PROGRAM"
LEVEL_COMPLETED_PROGRAM_OBJECT = "LEVEL_COMPLETED_PROGRAM"
# (STARTED / ENDED / RESTARTED / RESUMED / LEAVED)
LEVEL_OBJECT = "LEVEL"
# (CHANGED)
EXECUTION_SPEED_SLIDE_OBJECT = "EXECUTION_SPEED_SLIDE"
# (ASKED / RECEIVED)
ASSISTANT_HELP_OBJECT = "ASSISTANT_HELP"
# (RECEIVED)
TEACHER_HELP_OBJECT = "TEACHER_HELP"

# LEVEL values
LEVEL_1 = "1"
LEVEL_2 = "2"
LEVEL_3 = "3"
LEVEL_4 = "4"
LEVEL_5 = "5"
LEVEL_6 = "6"
LEVEL_7 = "7"
LEVEL_8 = "8"

# REASON values
# (LEVEL_LOST_PROGRAM)
LEVEL_LOST_SPIKE_TOUCH_REASON = "LEVEL_LOST_SPIKE_TOUCH"
LEVEL_LOST_BARREL_EXPLOSION_REASON = "LEVEL_LOST_BARREL_EXPLOSION"
LEVEL_LOST_OTHER_PIRATE_SHOT_REASON = "LEVEL_LOST_OTHER_PIRATE_SHOT"
# (GAME_ERROR_PROGRAM)
GAME_ERROR_OPEN_CHEST_LOCATION = "GAME_ERROR_OPEN_CHEST_LOCATION_REASON"
GAME_ERROR_OPEN_CHEST_KEY = "GAME_ERROR_OPEN_CHEST_KEY_REASON"
GAME_ERROR_READ_MESSAGE_LOCATION = "GAME_ERROR_READ_MESSAGE_LOCATION_REASON"
GAME_ERROR_WALK_LOCATION = "GAME_ERROR_WALK_LOCATION_REASON"
GAME_ERROR_NOT_ALLOWED_FUNCTION = "GAME_ERROR_NOT_ALLOWED_FUNCTION_REASON"
GAME_ERROR_FUNCTION_PARAMETERS = "GAME_ERROR_FUNCTION_PARAMETERS_REASON"

# GROUP ID values
GROUP_A="A"
GROUP_B="B"
GROUP_C="C"