# Used constants
GAME_ID="game"
STUDENT_ID="student"
GROUP_ID="group"
GROUP_A="A"
GROUP_B="B"
GROUP_C="C"

# Students of the experimentation
# BOU school
BOU_2_2 = [
    {GAME_ID:"8RfZ6hg", STUDENT_ID:1, GROUP_ID:GROUP_A},
    {GAME_ID:"eXr8PEA", STUDENT_ID:2, GROUP_ID:GROUP_A},
    {GAME_ID:"iFaENtA", STUDENT_ID:3, GROUP_ID:GROUP_A},
    # {GAME_ID:"fEZVGKe", STUDENT_ID:4, GROUP_ID:GROUP_A},# MISSED ['BOU_2_2_S3']
    {GAME_ID:"8u4e2F7", STUDENT_ID:5, GROUP_ID:GROUP_A},
    {GAME_ID:"Pe67mbr", STUDENT_ID:6, GROUP_ID:GROUP_A},
    {GAME_ID:"Xx49JVJ", STUDENT_ID:7, GROUP_ID:GROUP_A},
    {GAME_ID:"dSt33nR", STUDENT_ID:8, GROUP_ID:GROUP_A},
    # {GAME_ID:"1bJ5n1W", STUDENT_ID:9, GROUP_ID:GROUP_A}, # MISSED ['BOU_2_2_S1']
    {GAME_ID:"CQZ8NmB", STUDENT_ID:10, GROUP_ID:GROUP_A},
    {GAME_ID:"sfGvzLA", STUDENT_ID:11, GROUP_ID:GROUP_A},
    {GAME_ID:"hYkcJjn", STUDENT_ID:12, GROUP_ID:GROUP_A},
    {GAME_ID:"ENgmxPt", STUDENT_ID:13, GROUP_ID:GROUP_A},
    {GAME_ID:"SSD3YqX", STUDENT_ID:14, GROUP_ID:GROUP_A},
    {GAME_ID:"5TRGen7", STUDENT_ID:15, GROUP_ID:GROUP_A}, # Missing post-test
    {GAME_ID:"7QFcVsk", STUDENT_ID:17, GROUP_ID:GROUP_A},
    {GAME_ID:"cUjpKiJ", STUDENT_ID:18, GROUP_ID:GROUP_A},
    {GAME_ID:"rYt3SC4", STUDENT_ID:19, GROUP_ID:GROUP_A},
    # {GAME_ID:"9TuRvk7", STUDENT_ID:20, GROUP_ID:GROUP_A}, # MISSED ['BOU_2_2_S1']
    {GAME_ID:"Zh4E6y6", STUDENT_ID:21, GROUP_ID:GROUP_A},
    {GAME_ID:"ddCJX43", STUDENT_ID:22, GROUP_ID:GROUP_A},
    {GAME_ID:"PeBJsq3", STUDENT_ID:23, GROUP_ID:GROUP_A},
    {GAME_ID:"qFzER16", STUDENT_ID:24, GROUP_ID:GROUP_A},
    {GAME_ID:"gu9qmRU", STUDENT_ID:25, GROUP_ID:GROUP_A},
    {GAME_ID:"zutELnn", STUDENT_ID:26, GROUP_ID:GROUP_A},
    {GAME_ID:"6nHDjww", STUDENT_ID:27, GROUP_ID:GROUP_A},
    {GAME_ID:"p8qLZd7", STUDENT_ID:28, GROUP_ID:GROUP_A},
    {GAME_ID:"xBR3GQf", STUDENT_ID:30, GROUP_ID:GROUP_A},
    {GAME_ID:"3juU4tY", STUDENT_ID:31, GROUP_ID:GROUP_A}, # Finished level 8 after S3 => Not a problem traces cut after S3
    {GAME_ID:"dfs6ZJu", STUDENT_ID:32, GROUP_ID:GROUP_A},
    {GAME_ID:"H2YLnqj", STUDENT_ID:33, GROUP_ID:GROUP_A}, # Progression on level 7 after S3 => Not a problem trace cut after S3
    #  {GAME_ID:"WsAM7ds", STUDENT_ID:34, GROUP_ID:GROUP_A}, # MISSED ['BOU_2_2_S3']
    {GAME_ID:"ys2Rrqf", STUDENT_ID:35, GROUP_ID:GROUP_A},
    {GAME_ID:"qwT6WCs", STUDENT_ID:36, GROUP_ID:GROUP_A},
]
BOU_2_5 = [
    {GAME_ID:"J6davsE", STUDENT_ID:41, GROUP_ID:GROUP_B}, 
    {GAME_ID:"FPJCjd3", STUDENT_ID:42, GROUP_ID:GROUP_B}, 
    {GAME_ID:"Arxwr9G", STUDENT_ID:43, GROUP_ID:GROUP_B}, 
    {GAME_ID:"uM8NmNh", STUDENT_ID:44, GROUP_ID:GROUP_B}, 
    # {GAME_ID:"iGdTHMu", STUDENT_ID:45, GROUP_ID:GROUP_B}, # MISSED ['BOU_2_5_S2', 'BOU_2_5_S3']
    {GAME_ID:"CmQ3bi3", STUDENT_ID:46, GROUP_ID:GROUP_B}, 
    {GAME_ID:"rVUtbKs", STUDENT_ID:47, GROUP_ID:GROUP_B}, 
    {GAME_ID:"hFREZ2d", STUDENT_ID:48, GROUP_ID:GROUP_B}, 
    {GAME_ID:"HvEZmBm", STUDENT_ID:49, GROUP_ID:GROUP_B}, 
    {GAME_ID:"aBxXFta", STUDENT_ID:51, GROUP_ID:GROUP_B}, 
    {GAME_ID:"CCbUYFz", STUDENT_ID:52, GROUP_ID:GROUP_B}, 
    # {GAME_ID:"88dgwcP", STUDENT_ID:53, GROUP_ID:GROUP_B}, # MISSED ['BOU_2_5_S2']
    # {GAME_ID:"M39dVWF", STUDENT_ID:54, GROUP_ID:GROUP_B}, # MISSED ['BOU_2_5_S2']
    # {GAME_ID:"vNnC6qz", STUDENT_ID:55, GROUP_ID:GROUP_B}, # MISSED ['BOU_2_5_S2', 'BOU_2_5_S3']
    {GAME_ID:"cMC1A7b", STUDENT_ID:56, GROUP_ID:GROUP_B}, 
    {GAME_ID:"cxnpuAg", STUDENT_ID:57, GROUP_ID:GROUP_B}, 
    {GAME_ID:"fu46Vr2", STUDENT_ID:58, GROUP_ID:GROUP_B}, 
    # {GAME_ID:"qwujtFm", STUDENT_ID:59, GROUP_ID:GROUP_B}, # MISSED ['BOU_2_5_S2', 'BOU_2_5_S3']
    {GAME_ID:"tTYLjcq", STUDENT_ID:60, GROUP_ID:GROUP_B}, 
    {GAME_ID:"RntzaVJ", STUDENT_ID:61, GROUP_ID:GROUP_B}, 
    {GAME_ID:"xDvJGMG", STUDENT_ID:62, GROUP_ID:GROUP_B}, 
    {GAME_ID:"PuDNWgY", STUDENT_ID:63, GROUP_ID:GROUP_B}, 
    {GAME_ID:"p6UCEdQ", STUDENT_ID:64, GROUP_ID:GROUP_B}, 
    # {GAME_ID:"a5jbfgT", STUDENT_ID:65, GROUP_ID:GROUP_B}, # MISSED ['BOU_2_5_S1']
    {GAME_ID:"AyVKNE4", STUDENT_ID:66, GROUP_ID:GROUP_B}, 
    # {GAME_ID:"8SYEzT2", STUDENT_ID:67, GROUP_ID:GROUP_B}, # MISSED ['BOU_2_5_S2']
    {GAME_ID:"PMcjY1u", STUDENT_ID:68, GROUP_ID:GROUP_B}, 
    {GAME_ID:"guH7Ye8", STUDENT_ID:70, GROUP_ID:GROUP_B}, 
    {GAME_ID:"SzebmX3", STUDENT_ID:71, GROUP_ID:GROUP_B}, 
    {GAME_ID:"7Kq3hhp", STUDENT_ID:72, GROUP_ID:GROUP_B}, 
    {GAME_ID:"1y9zZYa", STUDENT_ID:73, GROUP_ID:GROUP_B}, 
    {GAME_ID:"W7Rp7uy", STUDENT_ID:74, GROUP_ID:GROUP_B}, 
    {GAME_ID:"PnMK39E", STUDENT_ID:75, GROUP_ID:GROUP_B}, 
    {GAME_ID:"Zci2BpV", STUDENT_ID:76, GROUP_ID:GROUP_B}, 
]
BOU_2_6 = [
    {GAME_ID:"j8mFqxs", STUDENT_ID:81, GROUP_ID:GROUP_B},
    {GAME_ID:"GLLtefW", STUDENT_ID:82, GROUP_ID:GROUP_B},
    {GAME_ID:"DTVfpyg", STUDENT_ID:83, GROUP_ID:GROUP_B},
    {GAME_ID:"cjEANz8", STUDENT_ID:84, GROUP_ID:GROUP_B},
    {GAME_ID:"Q4rB1rg", STUDENT_ID:85, GROUP_ID:GROUP_B},
    {GAME_ID:"prKhgDv", STUDENT_ID:86, GROUP_ID:GROUP_B},
    #  {GAME_ID:"rHDmnvF", STUDENT_ID:87, GROUP_ID:GROUP_B}, # MISSED ['BOU_2_6_S3']
    {GAME_ID:"n5qajKd", STUDENT_ID:88, GROUP_ID:GROUP_B},
    {GAME_ID:"XdF1dSM", STUDENT_ID:89, GROUP_ID:GROUP_B},
    #  {GAME_ID:"zJ7QaRC", STUDENT_ID:90, GROUP_ID:GROUP_B}, # MISSED ['BOU_2_6_S3']
    {GAME_ID:"qgNp8gw", STUDENT_ID:91, GROUP_ID:GROUP_B},
    {GAME_ID:"CDMMmNw", STUDENT_ID:92, GROUP_ID:GROUP_B},
    {GAME_ID:"sSB7JBV", STUDENT_ID:93, GROUP_ID:GROUP_B},
    {GAME_ID:"e42R9BV", STUDENT_ID:94, GROUP_ID:GROUP_B},
    {GAME_ID:"1hGqtuY", STUDENT_ID:95, GROUP_ID:GROUP_B},
    {GAME_ID:"MQeM7gq", STUDENT_ID:96, GROUP_ID:GROUP_B},
    {GAME_ID:"VZQ6XnQ", STUDENT_ID:97, GROUP_ID:GROUP_B},
    {GAME_ID:"acTX6Nf", STUDENT_ID:98, GROUP_ID:GROUP_B},
    {GAME_ID:"GAnpFJy", STUDENT_ID:99, GROUP_ID:GROUP_B},
    {GAME_ID:"VBJHtCU", STUDENT_ID:100, GROUP_ID:GROUP_B},
    {GAME_ID:"FhT62Vf", STUDENT_ID:101, GROUP_ID:GROUP_B},
    {GAME_ID:"KQn5X5q", STUDENT_ID:102, GROUP_ID:GROUP_B},
    {GAME_ID:"byCcupD", STUDENT_ID:103, GROUP_ID:GROUP_B},
    {GAME_ID:"9NeYms9", STUDENT_ID:104, GROUP_ID:GROUP_B}, # Played 8 minutes on level 5 (no game progression) at home between S2 and S3 => Keep student and delete traces between S2 and S3
    {GAME_ID:"UxmFsLw", STUDENT_ID:105, GROUP_ID:GROUP_B}, # Missing post-test (not submitted)
    {GAME_ID:"HGYW1j3", STUDENT_ID:106, GROUP_ID:GROUP_B},
    {GAME_ID:"ePVeTSE", STUDENT_ID:107, GROUP_ID:GROUP_B},
    {GAME_ID:"TW5ty6U", STUDENT_ID:108, GROUP_ID:GROUP_B}, # Missing post-test (not submitted)
    {GAME_ID:"MDkV1LG", STUDENT_ID:109, GROUP_ID:GROUP_B},
    {GAME_ID:"v2nLhC4", STUDENT_ID:110, GROUP_ID:GROUP_B},
    {GAME_ID:"39n6bvR", STUDENT_ID:111, GROUP_ID:GROUP_B},
    {GAME_ID:"esMZa32", STUDENT_ID:112, GROUP_ID:GROUP_B},
    {GAME_ID:"3ths5yR", STUDENT_ID:113, GROUP_ID:GROUP_B},
    {GAME_ID:"r6EBx5p", STUDENT_ID:114, GROUP_ID:GROUP_B},
    {GAME_ID:"AA1Uh2b", STUDENT_ID:115, GROUP_ID:GROUP_B},
]
# STA school
STA_M_1 = [
    # {GAME_ID:"VY4y5U5", STUDENT_ID:121, GROUP_ID:GROUP_B}, # MISSED ['STA_M_1_S2']
    # {GAME_ID:"3FtA4PJ", STUDENT_ID:122, GROUP_ID:GROUP_B}, # MISSED ['STA_M_1_S2']
    {GAME_ID:"mHWDsbL", STUDENT_ID:123, GROUP_ID:GROUP_B},
    {GAME_ID:"cBHhF9f", STUDENT_ID:124, GROUP_ID:GROUP_B},
    {GAME_ID:"PsRCVfX", STUDENT_ID:125, GROUP_ID:GROUP_B},
    {GAME_ID:"E2ENvRr", STUDENT_ID:126, GROUP_ID:GROUP_B},
    {GAME_ID:"b4cAb8f", STUDENT_ID:127, GROUP_ID:GROUP_B},
    {GAME_ID:"a9kUkGM", STUDENT_ID:128, GROUP_ID:GROUP_B},
    {GAME_ID:"Adm6D5h", STUDENT_ID:129, GROUP_ID:GROUP_B},
    {GAME_ID:"anPebzH", STUDENT_ID:130, GROUP_ID:GROUP_B},
    # {GAME_ID:"vV6BXis", STUDENT_ID:131, GROUP_ID:GROUP_B}, # MISSED ['STA_M_1_S1']
    {GAME_ID:"KMHUEfY", STUDENT_ID:132, GROUP_ID:GROUP_B},
    #  {GAME_ID:"bSL3fX4", STUDENT_ID:133, GROUP_ID:GROUP_B}, # MISSED ['STA_M_1_S1']
    {GAME_ID:"Db78MkE", STUDENT_ID:134, GROUP_ID:GROUP_B},
    {GAME_ID:"T5paQLr", STUDENT_ID:135, GROUP_ID:GROUP_B},
    {GAME_ID:"6iDc21P", STUDENT_ID:136, GROUP_ID:GROUP_B},
]
STA_M_2 = [
    {GAME_ID:"MmeWUFy", STUDENT_ID:141, GROUP_ID:GROUP_A}, 
    {GAME_ID:"4pGbimB", STUDENT_ID:142, GROUP_ID:GROUP_A},
    {GAME_ID:"h1b9UD1", STUDENT_ID:143, GROUP_ID:GROUP_A},
    {GAME_ID:"aWraDJr", STUDENT_ID:144, GROUP_ID:GROUP_A}, # Missing pre-test (not submitted)
    {GAME_ID:"bxb6Xyw", STUDENT_ID:145, GROUP_ID:GROUP_A},
    {GAME_ID:"6XkWRVi", STUDENT_ID:146, GROUP_ID:GROUP_A},
    {GAME_ID:"nP5j8Rc", STUDENT_ID:147, GROUP_ID:GROUP_A},
    {GAME_ID:"aKFus4E", STUDENT_ID:148, GROUP_ID:GROUP_A}, # Missing pre-test (not submitted)
    {GAME_ID:"mp965B3", STUDENT_ID:149, GROUP_ID:GROUP_A}, # Missing pre-test (not submitted)
    {GAME_ID:"QwQbEGy", STUDENT_ID:150, GROUP_ID:GROUP_A},
    # {GAME_ID:"FR2ZQpd", STUDENT_ID:151, GROUP_ID:GROUP_A}, # Missing pre-test (not submitted) # Played 15 minutes on level 5 (finished) between S1 ans S2 => Delete from study
    {GAME_ID:"Bb5wSKE", STUDENT_ID:152, GROUP_ID:GROUP_A},
    #  {GAME_ID:"jdz9xQy", STUDENT_ID:153, GROUP_ID:GROUP_A}, # MISSED ['STA_M_2_S1']
    {GAME_ID:"XE7zt3k", STUDENT_ID:154, GROUP_ID:GROUP_A},
    {GAME_ID:"Hfcka3u", STUDENT_ID:155, GROUP_ID:GROUP_A},
]
# PVA school
PVA_2_1_1 = [
    # {GAME_ID:"7f7AWsS", STUDENT_ID:161, GROUP_ID:GROUP_B}, # MISSED ['PVA_2_1_1_S2']
    {GAME_ID:"i78jhHm", STUDENT_ID:162, GROUP_ID:GROUP_B}, # Missing pre-test (not submitted)
    {GAME_ID:"MF3spWy", STUDENT_ID:163, GROUP_ID:GROUP_B}, # Missing post-test
    {GAME_ID:"HWfSquy", STUDENT_ID:164, GROUP_ID:GROUP_B},
    {GAME_ID:"2c5K3iE", STUDENT_ID:165, GROUP_ID:GROUP_B},
    # {GAME_ID:"CAaZfmX", STUDENT_ID:166, GROUP_ID:GROUP_B} # MISSED ['PVA_2_1_1_S2']
    {GAME_ID:"Z2qZM66", STUDENT_ID:170, GROUP_ID:GROUP_B},
    {GAME_ID:"P3M1jNq", STUDENT_ID:171, GROUP_ID:GROUP_B},
    {GAME_ID:"J3Ua1SU", STUDENT_ID:172, GROUP_ID:GROUP_B},
    # {GAME_ID:"A1aVQqi", STUDENT_ID:173, GROUP_ID:GROUP_B}, # MISSED ['PVA_2_1_1_S2', 'PVA_2_1_1_S3']
    {GAME_ID:"5LXXn9g", STUDENT_ID:174, GROUP_ID:GROUP_B},
    {GAME_ID:"gTZJHvv", STUDENT_ID:175, GROUP_ID:GROUP_B},
    # {GAME_ID:"jAxFcuK", STUDENT_ID:176, GROUP_ID:GROUP_B}, # MISSED ['PVA_2_1_1_S2']
]
PVA_2_1_2 = [
    # {GAME_ID:"C5BNZiG", STUDENT_ID:181, GROUP_ID:GROUP_A}, # MISSED ['PVA_2_1_2_S3']
    {GAME_ID:"khRVjHK", STUDENT_ID:182, GROUP_ID:GROUP_A},
    {GAME_ID:"2h5eSA9", STUDENT_ID:183, GROUP_ID:GROUP_A},
    {GAME_ID:"bDGN8sk", STUDENT_ID:185, GROUP_ID:GROUP_A},
    {GAME_ID:"GCxMbMp", STUDENT_ID:186, GROUP_ID:GROUP_A},
    {GAME_ID:"Mn17CMh", STUDENT_ID:188, GROUP_ID:GROUP_A},
    {GAME_ID:"GLKumS5", STUDENT_ID:189, GROUP_ID:GROUP_A},
    # {GAME_ID:"MhxSyyv", STUDENT_ID:190, GROUP_ID:GROUP_A}, # MISSED ['PVA_2_1_2_S2']
    {GAME_ID:"6YbdNKb", STUDENT_ID:191, GROUP_ID:GROUP_A},
    {GAME_ID:"iAKCi5n", STUDENT_ID:192, GROUP_ID:GROUP_A},
    {GAME_ID:"mXn9gMb", STUDENT_ID:193, GROUP_ID:GROUP_A},
    {GAME_ID:"AjLuDze", STUDENT_ID:194, GROUP_ID:GROUP_A}, # Missing post-test
    {GAME_ID:"uhgNDd7", STUDENT_ID:196, GROUP_ID:GROUP_A},
]
PVA_2_2_1 = [
    {GAME_ID:"1Y2RPm6", STUDENT_ID:202, GROUP_ID:GROUP_C},
    {GAME_ID:"BjMKXrN", STUDENT_ID:203, GROUP_ID:GROUP_C},
    {GAME_ID:"Cgt5tUz", STUDENT_ID:204, GROUP_ID:GROUP_C},
    {GAME_ID:"v4fJJri", STUDENT_ID:205, GROUP_ID:GROUP_C},
    {GAME_ID:"KUY6dRb", STUDENT_ID:206, GROUP_ID:GROUP_C},
    {GAME_ID:"SqnnK9b", STUDENT_ID:207, GROUP_ID:GROUP_C}, # Displayed level 5 (no progression) between S2 and S3 => Not a problem trace cut between S2 and S3
    {GAME_ID:"Keyt5cK", STUDENT_ID:208, GROUP_ID:GROUP_C}, # Game finished during S2 due to previous Python skills
    {GAME_ID:"UF66dCx", STUDENT_ID:209, GROUP_ID:GROUP_C},
    {GAME_ID:"VwKX5qU", STUDENT_ID:210, GROUP_ID:GROUP_C},
    {GAME_ID:"Cg8tFjb", STUDENT_ID:211, GROUP_ID:GROUP_C}, # Displayed level 4 (no action) between S2 and S3 => Not a problem trace cut between S2 and S3
    {GAME_ID:"S8zuqdE", STUDENT_ID:212, GROUP_ID:GROUP_C}, # Displayed level 3 (no progression) between S2 and S3 => Not a problem trace cut between S2 and S3
    {GAME_ID:"sRYi8Et", STUDENT_ID:213, GROUP_ID:GROUP_C},
    {GAME_ID:"rzmHDWh", STUDENT_ID:214, GROUP_ID:GROUP_C},
    {GAME_ID:"6dEpfjg", STUDENT_ID:215, GROUP_ID:GROUP_C},
    {GAME_ID:"9dQ8q87", STUDENT_ID:216, GROUP_ID:GROUP_C},
]
PVA_2_2_2 = [
    {GAME_ID:"2yudZTD", STUDENT_ID:221, GROUP_ID:GROUP_C}, # Game finished during S2, had no traces in S3
    # {GAME_ID:"uvjRYRw", STUDENT_ID:222, GROUP_ID:GROUP_C}, # MISSED ['PVA_2_2_2_S2']
    {GAME_ID:"sWWsfut", STUDENT_ID:223, GROUP_ID:GROUP_C},
    # {GAME_ID:"VmCqdXR", STUDENT_ID:224, GROUP_ID:GROUP_C},  # MISSED ['PVA_2_2_2_S1', 'PVA_2_2_2_S3']
    {GAME_ID:"spJgH1g", STUDENT_ID:225, GROUP_ID:GROUP_C},
    {GAME_ID:"H37dAEL", STUDENT_ID:226, GROUP_ID:GROUP_C},
    {GAME_ID:"SPCYvuq", STUDENT_ID:227, GROUP_ID:GROUP_C},
    # {GAME_ID:"T8xW1Hm", STUDENT_ID:228, GROUP_ID:GROUP_C}, # MISSED ['PVA_2_2_2_S1']
    {GAME_ID:"hZFpEL6", STUDENT_ID:229, GROUP_ID:GROUP_C},
    {GAME_ID:"6stGLrS", STUDENT_ID:230, GROUP_ID:GROUP_C},
    {GAME_ID:"2tYzhw3", STUDENT_ID:231, GROUP_ID:GROUP_C},
    {GAME_ID:"YyiDZYk", STUDENT_ID:232, GROUP_ID:GROUP_C},
    {GAME_ID:"sPe8xT6", STUDENT_ID:233, GROUP_ID:GROUP_C},
    {GAME_ID:"PptBrj7", STUDENT_ID:234, GROUP_ID:GROUP_C},
    # {GAME_ID:"DpYFAyG", STUDENT_ID:235, GROUP_ID:GROUP_C}, # MISSED ['PVA_2_2_2_S2', 'PVA_2_2_2_S3']
]

# LJS school
LJS_2_1_1 = [
    # {GAME_ID:"DNay2yX", STUDENT_ID:331, GROUP_ID:GROUP_B}, # Student with motor disability
    {GAME_ID:"NHH1mvK", STUDENT_ID:332, GROUP_ID:GROUP_B},
    # {GAME_ID:"ZtVUx32", STUDENT_ID:333, GROUP_ID:GROUP_B}, # Use Pyrates on his phone on S2
    {GAME_ID:"KHmqQwy", STUDENT_ID:335, GROUP_ID:GROUP_B},
    {GAME_ID:"FS182KA", STUDENT_ID:336, GROUP_ID:GROUP_B},
    {GAME_ID:"mVN8M7L", STUDENT_ID:337, GROUP_ID:GROUP_B},
    {GAME_ID:"SaFEHzh", STUDENT_ID:338, GROUP_ID:GROUP_B},
    # {GAME_ID:"56KYry3", STUDENT_ID:340, GROUP_ID:GROUP_B}, # MISSED ['LJS_2_1_1_S2']
    {GAME_ID:"f9CVMzw", STUDENT_ID:341, GROUP_ID:GROUP_B},
    {GAME_ID:"7mznE89", STUDENT_ID:342, GROUP_ID:GROUP_B},
    {GAME_ID:"Rbw7mLf", STUDENT_ID:343, GROUP_ID:GROUP_B},
    {GAME_ID:"CVtd56h", STUDENT_ID:344, GROUP_ID:GROUP_B},
    {GAME_ID:"L9cGdeG", STUDENT_ID:346, GROUP_ID:GROUP_B},
    {GAME_ID:"d1guUK9", STUDENT_ID:347, GROUP_ID:GROUP_B},
    {GAME_ID:"k18if8F", STUDENT_ID:349, GROUP_ID:GROUP_B},
    {GAME_ID:"Cb8yGv3", STUDENT_ID:350, GROUP_ID:GROUP_B},
]
LJS_2_1_2 = [
    {GAME_ID:"sfQak2Q", STUDENT_ID:351, GROUP_ID:GROUP_A},
    # {GAME_ID:"tQvd8C8", STUDENT_ID:352, GROUP_ID:GROUP_A}, # MISSED ['LJS_2_1_2_S2']
    {GAME_ID:"qyJAHJS", STUDENT_ID:354, GROUP_ID:GROUP_A},
    # {GAME_ID:"rUqxmtQ", STUDENT_ID:355, GROUP_ID:GROUP_A}, # Mixed traces due to computer clock modification during experiments
    {GAME_ID:"pjahSrM", STUDENT_ID:356, GROUP_ID:GROUP_A},
    {GAME_ID:"e5wqMLP", STUDENT_ID:357, GROUP_ID:GROUP_A},
    {GAME_ID:"QryMu4V", STUDENT_ID:358, GROUP_ID:GROUP_A},
    # {GAME_ID:"qFsErLu", STUDENT_ID:359, GROUP_ID:GROUP_A}, # Played two hours at home between S2 and S3 (finishing 3 levels) => Delete student from study
    {GAME_ID:"fXrKa4r", STUDENT_ID:360, GROUP_ID:GROUP_A}, # Missing pre-test
    {GAME_ID:"1ti3NXj", STUDENT_ID:361, GROUP_ID:GROUP_A}, # Missing pre-test
    {GAME_ID:"Pu9T7qe", STUDENT_ID:362, GROUP_ID:GROUP_A},
    {GAME_ID:"PGeRDcW", STUDENT_ID:363, GROUP_ID:GROUP_A}, # Missing post-test (not submitted)
    {GAME_ID:"eRhKLJR", STUDENT_ID:364, GROUP_ID:GROUP_A},
    {GAME_ID:"gjb3HpS", STUDENT_ID:365, GROUP_ID:GROUP_A}, # Dropout student
    {GAME_ID:"GX6CLq1", STUDENT_ID:366, GROUP_ID:GROUP_A},
    {GAME_ID:"idUGd5R", STUDENT_ID:367, GROUP_ID:GROUP_A},
    {GAME_ID:"pDdaB5G", STUDENT_ID:368, GROUP_ID:GROUP_A},
]
LJS_2_2_1 = [
    {GAME_ID:"SfUxmkD", STUDENT_ID:371, GROUP_ID:GROUP_C},
    {GAME_ID:"KAHbLAw", STUDENT_ID:372, GROUP_ID:GROUP_C},
    {GAME_ID:"zczudq1", STUDENT_ID:373, GROUP_ID:GROUP_C},
    {GAME_ID:"v95xW3Y", STUDENT_ID:374, GROUP_ID:GROUP_C},
    {GAME_ID:"Myxvk7Z", STUDENT_ID:375, GROUP_ID:GROUP_C},
    {GAME_ID:"tC22JmR", STUDENT_ID:376, GROUP_ID:GROUP_C},
    {GAME_ID:"GuZHZMu", STUDENT_ID:377, GROUP_ID:GROUP_C},
    {GAME_ID:"bDAKEwB", STUDENT_ID:378, GROUP_ID:GROUP_C},
    {GAME_ID:"ZUt47cy", STUDENT_ID:379, GROUP_ID:GROUP_C},
    {GAME_ID:"weYChqJ", STUDENT_ID:380, GROUP_ID:GROUP_C},
    {GAME_ID:"MsDYsvs", STUDENT_ID:381, GROUP_ID:GROUP_C},
    {GAME_ID:"BEMp5JP", STUDENT_ID:382, GROUP_ID:GROUP_C},
    {GAME_ID:"uzVgc1b", STUDENT_ID:383, GROUP_ID:GROUP_C},
    {GAME_ID:"vM6UPv8", STUDENT_ID:384, GROUP_ID:GROUP_C},
    {GAME_ID:"QNAZgEz", STUDENT_ID:385, GROUP_ID:GROUP_C},
    {GAME_ID:"1wY5pLR", STUDENT_ID:386, GROUP_ID:GROUP_C},
]
LJS_2_2_2 = [
    {GAME_ID:"2ENnNsR", STUDENT_ID:391, GROUP_ID:GROUP_C},
    {GAME_ID:"Eh5H9YW", STUDENT_ID:392, GROUP_ID:GROUP_C},
    {GAME_ID:"1FzzNWm", STUDENT_ID:393, GROUP_ID:GROUP_C},
    {GAME_ID:"wk49Atk", STUDENT_ID:394, GROUP_ID:GROUP_C},
    # {GAME_ID:"JkSDrRL", STUDENT_ID:395, GROUP_ID:GROUP_C}, # Use Pyrates on his phone on S2
    {GAME_ID:"icGxYBf", STUDENT_ID:396, GROUP_ID:GROUP_C},
    # {GAME_ID:"PTj73Ys", STUDENT_ID:397, GROUP_ID:GROUP_C}, # MISSED ['LJS_2_2_2_S2']
    {GAME_ID:"9zx7LYq", STUDENT_ID:398, GROUP_ID:GROUP_C},
    {GAME_ID:"ZWNLrMz", STUDENT_ID:399, GROUP_ID:GROUP_C}, # Missing post-test (not submitted)
    {GAME_ID:"JrdL7n5", STUDENT_ID:400, GROUP_ID:GROUP_C},
    {GAME_ID:"qqyGKF7", STUDENT_ID:401, GROUP_ID:GROUP_C},
    {GAME_ID:"yRA6bRD", STUDENT_ID:402, GROUP_ID:GROUP_C},
    {GAME_ID:"4a9beA3", STUDENT_ID:403, GROUP_ID:GROUP_C},
    {GAME_ID:"a4PDXpj", STUDENT_ID:404, GROUP_ID:GROUP_C},
    {GAME_ID:"8CrH8UQ", STUDENT_ID:405, GROUP_ID:GROUP_C},
    {GAME_ID:"Z6zpbKS", STUDENT_ID:406, GROUP_ID:GROUP_C},
    {GAME_ID:"Kh7kNCE", STUDENT_ID:407, GROUP_ID:GROUP_C},
    {GAME_ID:"6yHmuL8", STUDENT_ID:408, GROUP_ID:GROUP_C},
    {GAME_ID:"gpwbyum", STUDENT_ID:409, GROUP_ID:GROUP_C},
]

# LFIP school
LFIP_2_1 = [
    # {GAME_ID:"ZbLfCLh", STUDENT_ID:1001, GROUP_ID:GROUP_A},
    # # {GAME_ID:"?", STUDENT_ID:1002, GROUP_ID:GROUP_A}, # MISSED S1
    # {GAME_ID:"qCtKijh", STUDENT_ID:1003, GROUP_ID:GROUP_A},
    # {GAME_ID:"rCyrTR2", STUDENT_ID:1004, GROUP_ID:GROUP_A},
    # {GAME_ID:"X23guFm", STUDENT_ID:1005, GROUP_ID:GROUP_A},
    # {GAME_ID:"atsp3df", STUDENT_ID:1006, GROUP_ID:GROUP_A},
    # {GAME_ID:"FKdC8hW", STUDENT_ID:1007, GROUP_ID:GROUP_A},
    # {GAME_ID:"PmE63Nq", STUDENT_ID:1008, GROUP_ID:GROUP_A},
    # {GAME_ID:"xp59jiT", STUDENT_ID:1009, GROUP_ID:GROUP_A},
    # {GAME_ID:"LLefpdV", STUDENT_ID:1010, GROUP_ID:GROUP_A},
    # {GAME_ID:"mNACjAg", STUDENT_ID:1011, GROUP_ID:GROUP_A},
    # # {GAME_ID:"?", STUDENT_ID:1012, GROUP_ID:GROUP_A}, # MISSED S1
    # {GAME_ID:"6fHCJ6M", STUDENT_ID:1013, GROUP_ID:GROUP_A},
    # {GAME_ID:"UkjAFnx", STUDENT_ID:1014, GROUP_ID:GROUP_A},
    # {GAME_ID:"SNcVzJr", STUDENT_ID:1015, GROUP_ID:GROUP_A},
    # {GAME_ID:"3TD8KMz", STUDENT_ID:1016, GROUP_ID:GROUP_A},
    # {GAME_ID:"eS82S6b", STUDENT_ID:1017, GROUP_ID:GROUP_A},
    # {GAME_ID:"F7YP8Zi", STUDENT_ID:1018, GROUP_ID:GROUP_A},
    # {GAME_ID:"4RJ2VXX", STUDENT_ID:1019, GROUP_ID:GROUP_A},
]

LFIP_2_2 = [
    # {GAME_ID:"R7mj4Nf", STUDENT_ID:1020, GROUP_ID:GROUP_C},
    # {GAME_ID:"1EMfKTb", STUDENT_ID:1021, GROUP_ID:GROUP_C},
    # {GAME_ID:"q3U5J4E", STUDENT_ID:1022, GROUP_ID:GROUP_C},
    # {GAME_ID:"fZGhVJ7", STUDENT_ID:1023, GROUP_ID:GROUP_C},
    # {GAME_ID:"XQh5rwC", STUDENT_ID:1024, GROUP_ID:GROUP_C},
    # {GAME_ID:"4yLUesW", STUDENT_ID:1025, GROUP_ID:GROUP_C},
    # {GAME_ID:"bTNsY2t", STUDENT_ID:1026, GROUP_ID:GROUP_C},
    # {GAME_ID:"2kDTTfx", STUDENT_ID:1027, GROUP_ID:GROUP_C},
    # {GAME_ID:"haq95dd", STUDENT_ID:1028, GROUP_ID:GROUP_C},
    # {GAME_ID:"egpLT1h", STUDENT_ID:1029, GROUP_ID:GROUP_C},
    # {GAME_ID:"q5M89MW", STUDENT_ID:1030, GROUP_ID:GROUP_C},
    # {GAME_ID:"9HaDVrH", STUDENT_ID:1031, GROUP_ID:GROUP_C},
    # {GAME_ID:"WRrsFif", STUDENT_ID:1032, GROUP_ID:GROUP_C},
    # {GAME_ID:"kirL3gb", STUDENT_ID:1033, GROUP_ID:GROUP_C},
    # {GAME_ID:"kDYF3Ny", STUDENT_ID:1034, GROUP_ID:GROUP_C},
    # {GAME_ID:"LdgHdjc", STUDENT_ID:1035, GROUP_ID:GROUP_C},
    # {GAME_ID:"M6UWDAU", STUDENT_ID:1036, GROUP_ID:GROUP_C},
]

# All student lists grouped
ALL_STUDENTS = \
    BOU_2_2 + BOU_2_5 + BOU_2_6 \
    + STA_M_1 + STA_M_2 \
    + PVA_2_1_1 + PVA_2_1_2 + PVA_2_2_1 + PVA_2_2_2 \
    + LJS_2_1_1 + LJS_2_1_2 + LJS_2_2_1 + LJS_2_2_2 \
    + LFIP_2_1 + LFIP_2_2

# Class mapping dictionary
CLASS_MAPPING = {
    "BOU_2_2": BOU_2_2,
    "BOU_2_5": BOU_2_5,
    "BOU_2_6": BOU_2_6,
    "STA_M_1": STA_M_1,
    "STA_M_2": STA_M_2,
    "PVA_2_1_1" : PVA_2_1_1,
    "PVA_2_1_2" : PVA_2_1_2,
    "PVA_2_2_1" : PVA_2_2_1,
    "PVA_2_2_2" : PVA_2_2_2,
    "LJS_2_1_1" : LJS_2_1_1,
    "LJS_2_1_2" : LJS_2_1_2,
    "LJS_2_2_1" : LJS_2_2_1,
    "LJS_2_2_2" : LJS_2_2_2,
    "LFIP_2_1" : LFIP_2_1,
    "LFIP_2_2" : LFIP_2_2,
}